version: "4.29"

services:
  angular-app:
    build: .
    ports:
      - "4201:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=4200
      - DOCKER_ENV=true
    networks:
      - mfe-network

networks:
  mfe-network:
    external: true
