version: "3.8"

services:
  lgs-mfe-container:
    image: lgs-mfe-container:latest
    ports:
      - "4200:4200"
    networks:
      - mfe-network
    environment:
      - NODE_ENV=production
      - PORT=4200
    deploy:
      replicas: 3
      update_config:
        parallelism: 1 # Atualiza 1 por vez
        delay: 10s # Espera 10s entre atualizações
        order: start-first # Inicia nova antes de parar antiga
        failure_action: rollback
        monitor: 60s # Monitora por 60s
        max_failure_ratio: 0.3 # Máximo 30% de falhas
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  lgs-mfe-catalog:
    image: lgs-mfe-catalog:latest
    ports:
      - "4201:4200"
    networks:
      - mfe-network
    environment:
      - NODE_ENV=production
      - PORT=4200
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  lgs-mfe-cart:
    image: lgs-mfe-cart:latest
    ports:
      - "4202:4200"
    networks:
      - mfe-network
    environment:
      - NODE_ENV=production
      - PORT=4200
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mfe-network
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  mfe-network:
    driver: overlay
    attachable: true
