on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_OWNER: lgjo

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Rename Dockerfile for production
        if: github.ref == 'refs/heads/main'
        run: mv Dockerfile.prod Dockerfile
      - name: Build e push das imagens
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/lgs-mfe-container ./lgs-mfe-container
          docker build -t $REGISTRY/$IMAGE_OWNER/lgs-mfe-catalog ./lgs-mfe-catalog
          docker build -t $REGISTRY/$IMAGE_OWNER/lgs-mfe-cart ./lgs-mfe-cart

          docker push $REGISTRY/$IMAGE_OWNER/lgs-mfe-container
          docker push $REGISTRY/$IMAGE_OWNER/lgs-mfe-catalog
          docker push $REGISTRY/$IMAGE_OWNER/lgs-mfe-cart
      - name: Deploy no servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull $REGISTRY/$IMAGE_OWNER/lgs-mfe-container
            docker pull $REGISTRY/$IMAGE_OWNER/lgs-mfe-catalog
            docker pull $REGISTRY/$IMAGE_OWNER/lgs-mfe-cart

            docker compose -f /caminho/producao/docker-compose.yml up -d --remove-orphans