on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_OWNER: lgjo

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Rename Dockerfile for production
        if: github.ref == 'refs/heads/main'
        run: |
          mv ./lgs-mfe-container/Dockerfile.prod ./lgs-mfe-container/Dockerfile
          mv ./lgs-mfe-catalog/Dockerfile.prod ./lgs-mfe-catalog/Dockerfile
          mv ./lgs-mfe-cart/Dockerfile.prod ./lgs-mfe-cart/Dockerfile

      - name: Build e push das imagens
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/lgs-mfe-container ./lgs-mfe-container
          docker build -t $REGISTRY/$IMAGE_OWNER/lgs-mfe-catalog ./lgs-mfe-catalog
          docker build -t $REGISTRY/$IMAGE_OWNER/lgs-mfe-cart ./lgs-mfe-cart

          docker push $REGISTRY/$IMAGE_OWNER/lgs-mfe-container
          docker push $REGISTRY/$IMAGE_OWNER/lgs-mfe-catalog
          docker push $REGISTRY/$IMAGE_OWNER/lgs-mfe-cart